import { promises as fs, createReadStream } from "node:fs";
import path from "node:path";
import { Readable } from "node:stream";
import { env } from "./env";

export type StoredObject = {
  body: Readable;
  contentType: string;
  size: number;
};

export interface StorageDriver {
  readonly name: "local" | "s3";
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<StoredObject | null>;
  delete(key: string): Promise<void>;
  /** Some drivers can hand the browser a short-lived direct URL instead. */
  signedUrl?(key: string, expiresInSeconds: number): Promise<string>;
}

// ---------------------------------------------------------------------------
// Local disk — development, or a VPS with a mounted volume
// ---------------------------------------------------------------------------

class LocalDriver implements StorageDriver {
  readonly name = "local" as const;
  private readonly root = path.resolve(process.cwd(), env.STORAGE_LOCAL_DIR);

  /** Keys are generated by the app, but never trust one into a path anyway. */
  private resolve(key: string): string {
    const full = path.resolve(this.root, key);
    if (full !== this.root && !full.startsWith(this.root + path.sep)) {
      throw new Error("Refusing to access a path outside the storage root.");
    }
    return full;
  }

  async put(key: string, body: Buffer, _contentType: string): Promise<void> {
    const full = this.resolve(key);
    await fs.mkdir(path.dirname(full), { recursive: true });
    await fs.writeFile(full, body);
  }

  async get(key: string): Promise<StoredObject | null> {
    const full = this.resolve(key);
    try {
      const stat = await fs.stat(full);
      return {
        body: createReadStream(full),
        contentType: contentTypeFromKey(key),
        size: stat.size,
      };
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    try {
      await fs.unlink(this.resolve(key));
    } catch {
      // Already gone — deletion is idempotent.
    }
  }
}

// ---------------------------------------------------------------------------
// S3-compatible — Cloudflare R2, AWS S3, Supabase Storage, MinIO, B2
// ---------------------------------------------------------------------------

class S3Driver implements StorageDriver {
  readonly name = "s3" as const;
  private client: import("@aws-sdk/client-s3").S3Client | null = null;

  private async getClient() {
    if (!this.client) {
      const { S3Client } = await import("@aws-sdk/client-s3");
      this.client = new S3Client({
        region: env.S3_REGION,
        endpoint: env.S3_ENDPOINT || undefined,
        forcePathStyle: env.s3ForcePathStyle,
        credentials: {
          accessKeyId: env.S3_ACCESS_KEY_ID!,
          secretAccessKey: env.S3_SECRET_ACCESS_KEY!,
        },
      });
    }
    return this.client;
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    const { PutObjectCommand } = await import("@aws-sdk/client-s3");
    const client = await this.getClient();
    await client.send(
      new PutObjectCommand({
        Bucket: env.S3_BUCKET!,
        Key: key,
        Body: body,
        ContentType: contentType,
        // The bucket itself must stay private; access is only ever granted
        // through a short-lived signed URL or the authenticated proxy.
        CacheControl: "private, max-age=31536000, immutable",
      }),
    );
  }

  async get(key: string): Promise<StoredObject | null> {
    const { GetObjectCommand } = await import("@aws-sdk/client-s3");
    const client = await this.getClient();
    try {
      const res = await client.send(new GetObjectCommand({ Bucket: env.S3_BUCKET!, Key: key }));
      if (!res.Body) return null;
      return {
        body: res.Body as Readable,
        contentType: res.ContentType ?? contentTypeFromKey(key),
        size: res.ContentLength ?? 0,
      };
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    const { DeleteObjectCommand } = await import("@aws-sdk/client-s3");
    const client = await this.getClient();
    try {
      await client.send(new DeleteObjectCommand({ Bucket: env.S3_BUCKET!, Key: key }));
    } catch {
      // Idempotent.
    }
  }

  async signedUrl(key: string, expiresInSeconds: number): Promise<string> {
    const { GetObjectCommand } = await import("@aws-sdk/client-s3");
    const { getSignedUrl } = await import("@aws-sdk/s3-request-presigner");
    const client = await this.getClient();
    return getSignedUrl(client, new GetObjectCommand({ Bucket: env.S3_BUCKET!, Key: key }), {
      expiresIn: expiresInSeconds,
    });
  }
}

// ---------------------------------------------------------------------------

function contentTypeFromKey(key: string): string {
  const ext = path.extname(key).toLowerCase();
  switch (ext) {
    case ".jpg":
    case ".jpeg":
      return "image/jpeg";
    case ".png":
      return "image/png";
    case ".webp":
      return "image/webp";
    case ".avif":
      return "image/avif";
    case ".gif":
      return "image/gif";
    case ".zip":
      return "application/zip";
    case ".json":
      return "application/json";
    default:
      return "application/octet-stream";
  }
}

const globalForStorage = globalThis as unknown as { storage?: StorageDriver };

export const storage: StorageDriver =
  globalForStorage.storage ?? (env.STORAGE_DRIVER === "s3" ? new S3Driver() : new LocalDriver());

if (!env.isProduction) globalForStorage.storage = storage;

/** Deterministic key layout keeps every object traceable to one space. */
export function mediaKey(spaceId: string | null, mediaId: string, variant: "original" | "thumb", ext: string) {
  const scope = spaceId ? `spaces/${spaceId}` : "users";
  return `${scope}/media/${mediaId}/${variant}.${ext}`;
}
